name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Calculate coverage
      run: |
        lein cloverage --codecov
        bash <(curl -s https://codecov.io/bash)
